use_frameworks!

target 'ZWSToAppStore_Example' do
  pod 'ZWSToAppStore', :path => '../'

  target 'ZWSToAppStore_Tests' do
  pod 'ZWSToAppStore', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
